package com.fypool.repository;

import com.fypool.model.AdminCheckCertificateMessage;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 08/10/2017
*/
@Repository
public interface AdminCheckCertificateMessageRepository extends JpaRepository<AdminCheckCertificateMessage, Integer> {

}
