package com.fypool.repository;

import com.fypool.model.ArticleContent;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 31/10/2017
*/
@Repository
public interface ArticleContentRepository extends JpaRepository<ArticleContent, Integer> {

}
