package com.fypool.repository;

import com.fypool.model.Accounting;
import com.fypool.model.Balance;
import com.fypool.model.Task;
import com.fypool.model.User;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;

/**
* Generated by Spring Data Generator on 12/10/2017
*/
@Repository
public interface BalanceRepository extends JpaRepository<Balance, Integer> , JpaSpecificationExecutor<Balance> {
    //判断用户是否有过某笔款项
    Boolean existsByVariationAndAccountingAndTaskAndUser(BigDecimal variation, Accounting accounting,Task task,User user);

    //判断用户是否有过某笔款项，不带金额参数
    Boolean existsByAccountingAndTaskAndUser(Accounting accounting,Task task,User user);

    //判断任务是否有过某笔款项，不带用户和金额，这样才是最安全的，确定一个任务只会有一种类型的款项
    Boolean existsByAccountingAndTask(Accounting accounting,Task task);

    Page<Balance> findAllByUser(User user, Pageable pageable);

}
