package com.fypool.repository;

import com.fypool.model.Bill;
import com.fypool.model.Task;
import com.fypool.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 02/11/2017
*/
@Repository
public interface BillRepository extends JpaRepository<Bill, Integer>, JpaSpecificationExecutor<Bill> {
    Bill findByIdAndUser(Integer id,User user);
    Bill findByIdAndUserAndPay(Integer id,User user,Integer pay);

    List<Bill> findAllByUserAndPay(User user,Integer pay);
    List<Bill> findAllBySend(Integer send);
    List<Bill> findAllBySendAndType(Integer send,Integer type);
    List<Bill> findAllBySendAndTypeAndIdIn(Integer send,Integer type,List<Integer> ids);

    Boolean existsByIdAndUser(Integer id,User user);
    Integer countBillByPayAndUser(Integer pay,User user);

    Bill findByMonthAndUser(String month,User user);
}
