package com.fypool.repository;

import com.fypool.model.Company;
import com.fypool.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 08/10/2017
*/
@Repository
public interface CompanyRepository extends JpaRepository<Company, Integer> {
    Company findByUser(User user);
    Boolean existsByLicense(String license);
}
