package com.fypool.repository;

import com.fypool.model.CustomerService;
import com.fypool.model.User;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 22/11/2017
*/
@Repository
public interface CustomerServiceRepository extends JpaRepository<CustomerService, Integer> {
    Page<CustomerService> findAll(Pageable pageable);
    List<CustomerService> findAllByOnline(Integer online);

    Boolean existsByUser(User user);
}
