package com.fypool.repository;

import com.fypool.model.Education;
import com.fypool.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import javax.transaction.Transactional;
import java.util.List;

/**
* Generated by Spring Data Generator on 29/09/2017
*/
@Repository
public interface EducationRepository extends JpaRepository<Education, Integer> {
    List<Education> findByUser(User user);


    //在批量删除的时候，要加事务！！！
    @Transactional
    List<Education> deleteAllByUser(User user);
}
