package com.fypool.repository;

import com.fypool.model.FileClean;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 04/12/2017
*/
@Repository
public interface FileCleanRepository extends JpaRepository<FileClean, Integer> {

}
