package com.fypool.repository;

import com.fypool.model.Illegal;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 23/10/2017
*/
@Repository
public interface IllegalRepository extends JpaRepository<Illegal, Integer> {

}
