package com.fypool.repository;

import com.fypool.model.Invite;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 08/11/2017
*/
@Repository
public interface InviteRepository extends JpaRepository<Invite, Integer> {

}
