package com.fypool.repository;

import com.fypool.model.InvoiceRequest;
import com.fypool.model.Task;
import com.fypool.model.VipTask;
import org.springframework.data.domain.Page;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import org.springframework.data.domain.Pageable;

/**
* Generated by Spring Data Generator on 09/11/2017
*/
@Repository
public interface InvoiceRequestRepository extends JpaRepository<InvoiceRequest, Integer>, JpaSpecificationExecutor<InvoiceRequest> {
    InvoiceRequest findByTask(Task task);
    InvoiceRequest findByVipTask(VipTask vipTask);
    Boolean existsByTask(Task task);
    Boolean existsByVipTask(VipTask vipTask);

    Page<InvoiceRequest> findAll(Pageable pageable);
    Page<InvoiceRequest> findAllByResult(Integer result,Pageable pageable);
}
