package com.fypool.repository;

import com.fypool.model.Invoice;
import com.fypool.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 08/11/2017
*/
@Repository
public interface InvoiceRepository extends JpaRepository<Invoice, Integer> {
    List<Invoice> findByUserAndDeleted(User user,Integer deleted);
    Invoice findByUserAndDeletedAndId(User user,Integer deleted,Integer id);
    Integer countAllByUserAndDeleted(User user,Integer deleted);
}
