package com.fypool.repository;

import com.fypool.model.LanguageGroup;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 29/09/2017
*/
@Repository
public interface LanguageGroupRepository extends JpaRepository<LanguageGroup, Integer> {
}
