package com.fypool.repository;

import com.fypool.model.PersistentLogins;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 09/10/2017
*/
@Repository
public interface PersistentLoginsRepository extends JpaRepository<PersistentLogins, String> {

}
