package com.fypool.repository;

import com.fypool.model.LanguageGroup;
import com.fypool.model.Price;
import com.fypool.model.Quality;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 11/10/2017
*/
@Repository
public interface PriceRepository extends JpaRepository<Price, Integer> {
    Price findByLanguageGroupAndQuality(LanguageGroup languageGroup,Quality quality);
}
