package com.fypool.repository;

import com.fypool.model.Product;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 05/11/2017
*/
@Repository
public interface ProductRepository extends JpaRepository<Product, Integer> {
    Product findByOutTradeNo(String outTradeNo);
    Product findByOutBizNo(String outBizNo);
}
