package com.fypool.repository;

import com.fypool.model.ReportIllegal;
import com.fypool.model.Task;
import com.fypool.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 23/10/2017
*/
@Repository
public interface ReportIllegalRepository extends JpaRepository<ReportIllegal, Integer>, JpaSpecificationExecutor<ReportIllegal> {
    Boolean existsByTaskAndUser(Task task, User user);
    ReportIllegal findByIdAndResult(Integer id,Integer result);
}
