package com.fypool.repository;

import com.fypool.model.SignatureRequest;
import com.fypool.model.Task;
import com.fypool.model.VipTask;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 09/11/2017
*/
@Repository
public interface SignatureRequestRepository extends JpaRepository<SignatureRequest, Integer> , JpaSpecificationExecutor<SignatureRequest> {
    SignatureRequest findByTask(Task task);
    Boolean existsByTask(Task task);
    Boolean existsByVipTask(VipTask vipTask);
    SignatureRequest findByVipTask(VipTask vipTask);
}
