package com.fypool.repository;

import com.fypool.model.SmsNotify;
import com.fypool.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.util.Date;

/**
* Generated by Spring Data Generator on 16/11/2017
*/
@Repository
public interface SmsNotifyRepository extends JpaRepository<SmsNotify, Integer> {

    SmsNotify findByUser(User user);

    @Modifying
    @Query("update SmsNotify set used = 0")
    @Transactional
    Integer updateUsed();
}
