package com.fypool.repository;

import com.fypool.model.TaskContent;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 11/10/2017
*/
@Repository
public interface TaskContentRepository extends JpaRepository<TaskContent, Integer> {

}
