package com.fypool.repository;

import com.fypool.model.LanguageGroup;
import com.fypool.model.Task;
import com.fypool.model.User;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
* Generated by Spring Data Generator on 11/10/2017
*/
@Repository
public interface TaskRepository extends JpaRepository<Task, Integer> , JpaSpecificationExecutor<Task> {
    //每隔半小时，检查置顶时间是否过期，设置spring boot定时任务，一天也就执行48次
    //如果过期，把top设置为0，
    Page<Task> findAllByUserAndOff(User user,Integer off,Pageable pageable);

    Page<Task> findAllByUserAndProcess_Process(User user,Integer process,Pageable pageable);

    Integer countAllByUserAndProcess_Process(User user,Integer process);


    //查找用户发布的所有任务
    Page<Task> findAllByUser(User user, Pageable pageable);

    Integer countAllByUser(User user);

    Task findByIdAndUser(Integer id,User user);
    Task findByIdAndOff(Integer id,Integer off);

    //为防止任务拥有者刷钱，还要增加任务状态属性来查找
    Task findByIdAndUserAndOff(Integer id,User user,Integer off);

    @Modifying
    @Query("update Task task set task.top = 0 where task.top = 1 and task.topTime < ?1")
    @Transactional
    Integer updateTop(Date now);

    Integer countByUser(User user);

    Integer countAllByUserAndOff(User user, Integer off);

}
