package com.fypool.repository;

import com.fypool.model.TaskInterpret;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 13/10/2017
*/
@Repository
public interface TaskInterpretRepository extends JpaRepository<TaskInterpret, Integer> {

}
