package com.fypool.repository;

import com.fypool.model.Task;
import com.fypool.model.Ticket;
import com.fypool.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
* Generated by Spring Data Generator on 08/11/2017
*/
@Repository
public interface TicketRepository extends JpaRepository<Ticket, Integer> {
    Integer countAllByUser(User user);
    List<Ticket> findAllByUserAndUsedAndLimitationLessThanEqualAndEndTimeAfter(User user, Integer used, BigDecimal limitation, Date date);
    Ticket findByIdAndUserAndUsedAndLimitationLessThanEqualAndEndTimeAfter(Integer id,User user, Integer used, BigDecimal limitation, Date date);

    Ticket findByUserAndIdAndEndTimeAfter(User user,Integer id,Date date);
    //一个任务只能使用一张优惠券，所以一个任务能找到唯一的一张优惠券
}
