package com.fypool.repository;

import com.fypool.model.VipPrice;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 01/11/2017
*/
@Repository
public interface VipPriceRepository extends JpaRepository<VipPrice, Integer> {

}
