package com.fypool.repository;

import com.fypool.model.Vip;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 01/11/2017
*/
@Repository
public interface VipRepository extends JpaRepository<Vip, Integer> {
    Vip findByUser_Username(String username);
    List<Vip> findAllByType(Integer type);
    Boolean existsByPath(String path);
}
