package com.fypool.repository;

import com.fypool.model.Bill;
import com.fypool.model.User;
import com.fypool.model.VipTask;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
* Generated by Spring Data Generator on 02/11/2017
*/
@Repository
public interface VipTaskRepository extends JpaRepository<VipTask, Integer>, JpaSpecificationExecutor<VipTask> {
     //判断用户是否有未出账单的vip任务，off=2
     Boolean existsByUserAndOff(User user,Integer off);

     List<VipTask> findAllByUserAndOff(User user, Integer off);

     VipTask findByIdAndUser(Integer id,User user);
     VipTask findByIdAndUserAndOff(Integer id,User user,Integer off);

     @Modifying
     @Query("update VipTask v set v.off = 3,v.bill = ?1 where v.user = ?2 and v.off = 2")
     @Transactional
     Integer updateOff(Bill bill, User user);

     Boolean existsByVipAttachment(String vipAttachment);
     Boolean existsByVipTask(String vipTask);

}
