package com.fypool.repository;

import com.fypool.model.Web;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 03/11/2017
*/
@Repository
public interface WebRepository extends JpaRepository<Web, Integer> {

}
