package com.fypool.manager;

import com.fypool.repository.AccountRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 11/10/2017
*/
@Component
public class AccountManager {

	@Autowired
	public AccountManager(AccountRepository accountRepository) {
		this.accountRepository = accountRepository;
	}

	private AccountRepository accountRepository;

}
