package com.fypool.manager;

import com.fypool.repository.AccountingRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/10/2017
*/
@Component
public class AccountingManager {

	@Autowired
	public AccountingManager(AccountingRepository accountingRepository) {
		this.accountingRepository = accountingRepository;
	}

	private AccountingRepository accountingRepository;

}
