package com.fypool.manager;

import com.fypool.repository.AddressRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 08/11/2017
*/
@Component
public class AddressManager {

	@Autowired
	public AddressManager(AddressRepository addressRepository) {
		this.addressRepository = addressRepository;
	}

	private AddressRepository addressRepository;

}
