package com.fypool.manager;

import com.fypool.repository.AdminCheckCertificateRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 29/09/2017
*/
@Component
public class AdminCheckCertificateManager {

	@Autowired
	public AdminCheckCertificateManager(AdminCheckCertificateRepository adminCheckCertificateRepository) {
		this.adminCheckCertificateRepository = adminCheckCertificateRepository;
	}

	private AdminCheckCertificateRepository adminCheckCertificateRepository;

}
