package com.fypool.manager;

import com.fypool.repository.AdminCheckCertificateMessageRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 08/10/2017
*/
@Component
public class AdminCheckCertificateMessageManager {

	@Autowired
	public AdminCheckCertificateMessageManager(AdminCheckCertificateMessageRepository adminCheckCertificateMessageRepository) {
		this.adminCheckCertificateMessageRepository = adminCheckCertificateMessageRepository;
	}

	private AdminCheckCertificateMessageRepository adminCheckCertificateMessageRepository;

}
