package com.fypool.manager;

import com.fypool.repository.ArticleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/10/2017
*/
@Component
public class ArticleManager {

	@Autowired
	public ArticleManager(ArticleRepository articleRepository) {
		this.articleRepository = articleRepository;
	}

	private ArticleRepository articleRepository;

}
