package com.fypool.manager;

import com.fypool.repository.ArticleContentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/10/2017
*/
@Component
public class ArticleContentManager {

	@Autowired
	public ArticleContentManager(ArticleContentRepository articleContentRepository) {
		this.articleContentRepository = articleContentRepository;
	}

	private ArticleContentRepository articleContentRepository;

}
