package com.fypool.manager;

import com.fypool.repository.AttributeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 29/09/2017
*/
@Component
public class AttributeManager {

	@Autowired
	public AttributeManager(AttributeRepository attributeRepository) {
		this.attributeRepository = attributeRepository;
	}

	private AttributeRepository attributeRepository;

}
