package com.fypool.manager;

import com.fypool.repository.BillRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 02/11/2017
*/
@Component
public class BillManager {

	@Autowired
	public BillManager(BillRepository billRepository) {
		this.billRepository = billRepository;
	}

	private BillRepository billRepository;

}
