package com.fypool.manager;

import com.fypool.repository.CatalogRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 31/10/2017
*/
@Component
public class CatalogManager {

	@Autowired
	public CatalogManager(CatalogRepository catalogRepository) {
		this.catalogRepository = catalogRepository;
	}

	private CatalogRepository catalogRepository;

}
