package com.fypool.manager;

import com.fypool.repository.CertificateRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 29/09/2017
*/
@Component
public class CertificateManager {

	@Autowired
	public CertificateManager(CertificateRepository certificateRepository) {
		this.certificateRepository = certificateRepository;
	}

	private CertificateRepository certificateRepository;

}
