package com.fypool.manager;

import com.fypool.repository.CertificateInfoRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 19/10/2017
*/
@Component
public class CertificateInfoManager {

	@Autowired
	public CertificateInfoManager(CertificateInfoRepository certificateInfoRepository) {
		this.certificateInfoRepository = certificateInfoRepository;
	}

	private CertificateInfoRepository certificateInfoRepository;

}
