package com.fypool.manager;

import com.fypool.repository.CertificatePictureRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 29/09/2017
*/
@Component
public class CertificatePictureManager {

	@Autowired
	public CertificatePictureManager(CertificatePictureRepository certificatePictureRepository) {
		this.certificatePictureRepository = certificatePictureRepository;
	}

	private CertificatePictureRepository certificatePictureRepository;

}
