package com.fypool.manager;

import com.fypool.repository.CompanyRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 08/10/2017
*/
@Component
public class CompanyManager {

	@Autowired
	public CompanyManager(CompanyRepository companyRepository) {
		this.companyRepository = companyRepository;
	}

	private CompanyRepository companyRepository;

}
