package com.fypool.manager;

import com.fypool.repository.CustomerServiceRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 22/11/2017
*/
@Component
public class CustomerServiceManager {

	@Autowired
	public CustomerServiceManager(CustomerServiceRepository customerServiceRepository) {
		this.customerServiceRepository = customerServiceRepository;
	}

	private CustomerServiceRepository customerServiceRepository;

}
