package com.fypool.manager;

import com.fypool.repository.EducationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 29/09/2017
*/
@Component
public class EducationManager {

	@Autowired
	public EducationManager(EducationRepository educationRepository) {
		this.educationRepository = educationRepository;
	}

	private EducationRepository educationRepository;

}
