package com.fypool.manager;

import com.fypool.repository.FileCleanRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 04/12/2017
*/
@Component
public class FileCleanManager {

	@Autowired
	public FileCleanManager(FileCleanRepository fileCleanRepository) {
		this.fileCleanRepository = fileCleanRepository;
	}

	private FileCleanRepository fileCleanRepository;

}
