package com.fypool.manager;

import com.fypool.repository.InviteRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 08/11/2017
*/
@Component
public class InviteManager {

	@Autowired
	public InviteManager(InviteRepository inviteRepository) {
		this.inviteRepository = inviteRepository;
	}

	private InviteRepository inviteRepository;

}
