package com.fypool.manager;

import com.fypool.repository.InvoiceRequestRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 09/11/2017
*/
@Component
public class InvoiceRequestManager {

	@Autowired
	public InvoiceRequestManager(InvoiceRequestRepository invoiceRequestRepository) {
		this.invoiceRequestRepository = invoiceRequestRepository;
	}

	private InvoiceRequestRepository invoiceRequestRepository;

}
