package com.fypool.manager;

import com.fypool.repository.InvoiceRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 08/11/2017
*/
@Component
public class InvoiceManager {

	@Autowired
	public InvoiceManager(InvoiceRepository InvoiceRepository) {
		this.InvoiceRepository = InvoiceRepository;
	}

	private InvoiceRepository InvoiceRepository;

}
