package com.fypool.manager;

import com.fypool.repository.LanguagesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 29/09/2017
*/
@Component
public class LanguagesManager {

	@Autowired
	public LanguagesManager(LanguagesRepository languagesRepository) {
		this.languagesRepository = languagesRepository;
	}

	private LanguagesRepository languagesRepository;

}
