package com.fypool.manager;

import com.fypool.repository.MhCityRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 29/09/2017
*/
@Component
public class MhCityManager {

	@Autowired
	public MhCityManager(MhCityRepository mhCityRepository) {
		this.mhCityRepository = mhCityRepository;
	}

	private MhCityRepository mhCityRepository;

}
