package com.fypool.manager;

import com.fypool.repository.PersistentLoginsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 09/10/2017
*/
@Component
public class PersistentLoginsManager {

	@Autowired
	public PersistentLoginsManager(PersistentLoginsRepository persistentLoginsRepository) {
		this.persistentLoginsRepository = persistentLoginsRepository;
	}

	private PersistentLoginsRepository persistentLoginsRepository;

}
