package com.fypool.manager;

import com.fypool.repository.PriceRangeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 16/10/2017
*/
@Component
public class PriceRangeManager {

	@Autowired
	public PriceRangeManager(PriceRangeRepository priceRangeRepository) {
		this.priceRangeRepository = priceRangeRepository;
	}

	private PriceRangeRepository priceRangeRepository;

}
