package com.fypool.manager;

import com.fypool.repository.PriceRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 11/10/2017
*/
@Component
public class PriceManager {

	@Autowired
	public PriceManager(PriceRepository priceRepository) {
		this.priceRepository = priceRepository;
	}

	private PriceRepository priceRepository;

}
