package com.fypool.manager;

import com.fypool.repository.ProcessRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 23/10/2017
*/
@Component
public class ProcessManager {

	@Autowired
	public ProcessManager(ProcessRepository processRepository) {
		this.processRepository = processRepository;
	}

	private ProcessRepository processRepository;

}
