package com.fypool.manager;

import com.fypool.repository.ProductRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 05/11/2017
*/
@Component
public class ProductManager {

	@Autowired
	public ProductManager(ProductRepository productRepository) {
		this.productRepository = productRepository;
	}

	private ProductRepository productRepository;

}
