package com.fypool.manager;

import com.fypool.repository.QualityRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 11/10/2017
*/
@Component
public class QualityManager {

	@Autowired
	public QualityManager(QualityRepository qualityRepository) {
		this.qualityRepository = qualityRepository;
	}

	private QualityRepository qualityRepository;

}
