package com.fypool.manager;

import com.fypool.repository.ReportIllegalRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 23/10/2017
*/
@Component
public class ReportIllegalManager {

	@Autowired
	public ReportIllegalManager(ReportIllegalRepository reportIllegalRepository) {
		this.reportIllegalRepository = reportIllegalRepository;
	}

	private ReportIllegalRepository reportIllegalRepository;

}
