package com.fypool.manager;

import com.fypool.repository.RoleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 29/09/2017
*/
@Component
public class RoleManager {

	@Autowired
	public RoleManager(RoleRepository roleRepository) {
		this.roleRepository = roleRepository;
	}

	private RoleRepository roleRepository;

}
