package com.fypool.manager;

import com.fypool.repository.SignatureRequestRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 09/11/2017
*/
@Component
public class SignatureRequestManager {

	@Autowired
	public SignatureRequestManager(SignatureRequestRepository signatureRequestRepository) {
		this.signatureRequestRepository = signatureRequestRepository;
	}

	private SignatureRequestRepository signatureRequestRepository;

}
