package com.fypool.manager;

import com.fypool.repository.SkilledFieldRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 29/09/2017
*/
@Component
public class SkilledFieldManager {

	@Autowired
	public SkilledFieldManager(SkilledFieldRepository skilledFieldRepository) {
		this.skilledFieldRepository = skilledFieldRepository;
	}

	private SkilledFieldRepository skilledFieldRepository;

}
