package com.fypool.manager;

import com.fypool.repository.SlideImageRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 03/11/2017
*/
@Component
public class SlideImageManager {

	@Autowired
	public SlideImageManager(SlideImageRepository slideImageRepository) {
		this.slideImageRepository = slideImageRepository;
	}

	private SlideImageRepository slideImageRepository;

}
