package com.fypool.manager;

import com.fypool.repository.SmsNotifyRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 16/11/2017
*/
@Component
public class SmsNotifyManager {

	@Autowired
	public SmsNotifyManager(SmsNotifyRepository smsNotifyRepository) {
		this.smsNotifyRepository = smsNotifyRepository;
	}

	private SmsNotifyRepository smsNotifyRepository;

}
