package com.fypool.manager;

import com.fypool.repository.TaskContentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 11/10/2017
*/
@Component
public class TaskContentManager {

	@Autowired
	public TaskContentManager(TaskContentRepository taskContentRepository) {
		this.taskContentRepository = taskContentRepository;
	}

	private TaskContentRepository taskContentRepository;

}
