package com.fypool.manager;

import com.fypool.repository.TaskInterpretRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 13/10/2017
*/
@Component
public class TaskInterpretManager {

	@Autowired
	public TaskInterpretManager(TaskInterpretRepository taskInterpretRepository) {
		this.taskInterpretRepository = taskInterpretRepository;
	}

	private TaskInterpretRepository taskInterpretRepository;

}
