package com.fypool.manager;

import com.fypool.repository.TaskRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 11/10/2017
*/
@Component
public class TaskManager {

	@Autowired
	public TaskManager(TaskRepository taskRepository) {
		this.taskRepository = taskRepository;
	}

	private TaskRepository taskRepository;

}
