package com.fypool.manager;

import com.fypool.repository.TaskUserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 23/10/2017
*/
@Component
public class TaskUserManager {

	@Autowired
	public TaskUserManager(TaskUserRepository taskUserRepository) {
		this.taskUserRepository = taskUserRepository;
	}

	private TaskUserRepository taskUserRepository;

}
