package com.fypool.manager;

import com.fypool.repository.TicketRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 08/11/2017
*/
@Component
public class TicketManager {

	@Autowired
	public TicketManager(TicketRepository ticketRepository) {
		this.ticketRepository = ticketRepository;
	}

	private TicketRepository ticketRepository;

}
