package com.fypool.manager;

import com.fypool.repository.TranslatePriceRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 29/09/2017
*/
@Component
public class TranslatePriceManager {

	@Autowired
	public TranslatePriceManager(TranslatePriceRepository translatePriceRepository) {
		this.translatePriceRepository = translatePriceRepository;
	}

	private TranslatePriceRepository translatePriceRepository;

}
