package com.fypool.manager;

import com.fypool.repository.UserInfoRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 29/09/2017
*/
@Component
public class UserInfoManager {

	@Autowired
	public UserInfoManager(UserInfoRepository userInfoRepository) {
		this.userInfoRepository = userInfoRepository;
	}

	private UserInfoRepository userInfoRepository;

}
