package com.fypool.manager;

import com.fypool.repository.VipRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 01/11/2017
*/
@Component
public class VipManager {

	@Autowired
	public VipManager(VipRepository vipRepository) {
		this.vipRepository = vipRepository;
	}

	private VipRepository vipRepository;

}
