package com.fypool.manager;

import com.fypool.repository.WebRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 03/11/2017
*/
@Component
public class WebManager {

	@Autowired
	public WebManager(WebRepository webRepository) {
		this.webRepository = webRepository;
	}

	private WebRepository webRepository;

}
